network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
    eth1: {}
    eth2: {}
    eth3: {}
    eth4: {}
    eth5: {}
  bridges:
    br-mgmt:
      interfaces: [eth1]
      addresses: [172.16.0.13/16]
    br-public:
      interfaces: [eth2]
      addresses: [192.168.200.13/24]
      gateway4: 192.168.200.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
    br-storage:
      interfaces: [eth3]
      addresses: [172.20.0.13/16]
    br-vxlan:
      interfaces: [eth4]
      addresses: [172.19.0.13/16]
    br-vlan:
      interfaces: [eth5]
      addresses: [172.18.0.13/16]
