network:
  version: 2
  renderer: networkd
  ethernets:
    eth0: {}          # no usado (por si acaso)
    eth1: {}          # parte de br-public, puente a Internet
    eth2: {}          # parte de br-mgmt
    eth3: {}          # parte de br-storage
    eth4: {}          # parte de br-vxlan
    eth5: {}          # parte de br-vlan
  bridges:
    br-public:
      interfaces: [eth1]
      addresses: [192.168.200.11/24]
      gateway4: 192.168.200.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
    br-mgmt:
      interfaces: [eth2]
      addresses: [172.16.0.11/16]
    br-storage:
      interfaces: [eth3]
      addresses: [172.20.0.11/16]
    br-vxlan:
      interfaces: [eth4]
      addresses: [172.19.0.11/16]