network:
  version: 2
  renderer: networkd
  ethernets:
    eth0: {}          # no usado
    eth1: {}          # br-public
    eth2: {}          # br-mgmt
    eth3: {}          # br-vxlan
    eth4: {}          # br-vlan
  bridges:
    br-public:
      interfaces: [eth1]
      addresses: [192.168.200.12/24]
      gateway4: 192.168.200.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
    br-mgmt:
      interfaces: [eth2]
      addresses: [172.16.0.12/16]
    br-vxlan:
      interfaces: [eth3]
      addresses: [172.19.0.12/16]
    br-vlan:
      interfaces: [eth4]
      addresses: [172.18.0.12/16]