network:
  version: 2
  renderer: networkd
  ethernets:
    eth0: {}          # no usado
    eth1: {}          # br-public
    eth2: {}          # br-mgmt
    eth3: {}          # br-storage
  bridges:
    br-public:
      interfaces: [eth1]
      addresses: [192.168.200.14/24]
      gateway4: 192.168.200.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
    br-mgmt:
      interfaces: [eth2]
      addresses: [172.16.0.14/16]
    br-storage:
      interfaces: [eth3]
      addresses: [172.20.0.14/16]